# Generated by Django 4.2.3 on 2023-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisinfectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_setup', models.IntegerField()),
                ('run_count', models.IntegerField()),
                ('master_ip', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrefilledData',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('YEAR', models.IntegerField()),
                ('MONTH', models.IntegerField()),
                ('DAY', models.IntegerField()),
                ('HOUR', models.IntegerField()),
                ('MIN', models.IntegerField()),
                ('ROOM', models.IntegerField()),
                ('PERCENTAGE', models.IntegerField()),
                ('DURATION', models.IntegerField()),
                ('IMAGE', models.TextField()),
                ('DATE', models.TextField()),
                ('STATUS', models.TextField()),
            ],
            options={
                'db_table': 'HAYSTACK_DISINFECT_REPORT',
            },
        ),
    ]
