# Generated by Django 4.2.3 on 2023-08-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YEAR', models.IntegerField()),
                ('MONTH', models.IntegerField()),
                ('DAY', models.IntegerField()),
                ('HOUR', models.IntegerField()),
                ('MIN', models.IntegerField()),
                ('ROOM', models.IntegerField()),
                ('PERCENTAGE', models.IntegerField()),
                ('DURATION', models.IntegerField()),
                ('IMAGE', models.TextField()),
                ('DATE', models.TextField()),
                ('STATUS', models.TextField()),
            ],
        ),
    ]
