# Generated by Django 4.2.3 on 2023-09-05 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
        migrations.DeleteModel(
            name='PrefilledData',
        ),
    ]
