# Generated by Django 4.2.3 on 2023-08-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_disinfectionrun_disinfect_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disinfectionrun',
            name='run_status',
        ),
    ]
