# Generated by Django 4.2.3 on 2023-09-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_newmodel_delete_prefilleddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('min', models.IntegerField()),
                ('room', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'robot_data_append_table',
            },
        ),
    ]
