# Generated by Django 4.2.3 on 2023-09-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_filtereddata_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='disinfectionrun',
            name='robot_name',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
    ]
