# Generated by Django 4.2.3 on 2023-09-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_disinfectionrun_robot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disinfectionrun',
            name='robot_name',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
